---
- name: dotmpe/user-conf-llm
  label: User-Conf repository for LLM
  description: Draft for tooling configuration and context specification
  shell:
    aliases:
      aider+user: |
        : Id usrtools_user-conf::docker-aider_als::aider+user
        [[ -d .local/user/data ]] || failerr "not in a basedir" || return;
        \builtin command aider \
         --no-show-release-notes --no-gitignore \
         --no-auto-commits \
         --no-dirty-commits \
         --no-attribute-author \
         --attribute-commit-message-author \
         --input-history-file .local/user/data/input/aider.input.history \
         --chat-history-file .local/user/data/chat/aider.chat.history.md \
         --config $HOME/.local/share/dotfiles/etc/aider/aider.conf.yml'

      aider+unsane: aider+user --no-show-model-warnings --auto-commits

      aider: 'aider+user'

      bashunit+llm+docs+update: |
        mkdir -p .local/agent &&
        curl -s https://bashunit.com/llms.txt \
          -o .local/agent/bashunit-docs-index.txt &&
        curl -s https://bashunit.com/llms-full.txt \
          -o .local/agent/bashunit-docs.txt

      bashunit+llm+skills+update:
        mkdir -p .claude/skills/bashunit &&
        curl -sL https://bashunit.com/bashunit-skill.md \
          -o .claude/skills/bashunit/SKILL.md

    scripts: {}
  scm-ignores: .gitignores
  source: dotmpe/user-conf-llm.git
  created: "[Fri 28] [35'26] [2026-08-28] [01:01Z]"
